# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectDream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(max_length=5000)),
                ('comment_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DreamComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish_time', models.DateTimeField(auto_now=True, null=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Dream')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='dream.DreamComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.IntegerField(blank=True, choices=[(1, '\u5199dream'), (2, '\u5199comment')], null=True, verbose_name='\u7528\u6237\u884c\u4e3a')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.DreamComment')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Dream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collectdream',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Dream'),
        ),
        migrations.AddField(
            model_name='collectdream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
